# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
  # - windows
julia:
  - 1.0.5
  # - 1.4.1
notifications:
  email: true
jobs:
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.0.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip