# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0.5
  - nightly
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  stage: "Documentation"
  julia: 1.0.5
  os: linux
  script:
    - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
    Pkg.instantiate()'
    - julia --project=docs/ docs/make.jl
